@startuml DarkStyle


!define BG_COLOR #555
!define BORDER_COLOR #EEE
!define FONT_COLOR #EEE
!define ARROW_COLOR #AAA

' include the general skinparams for both, light and dark
' to overwrite with the given settings
!include general.puml
@enduml