@startuml componentDiagram

package Presentation {
    [MainFrame] as MF
}

package Logic {
    [DataPreperator] as DP
}

MF -(0- DP

package DataAccess {
    [DataManager] as DM
}

DP -(0-- DM

package Data {
    database H2 {
        [Card]
        [CardSet]
    }
}

DM -(0 H2 : Hibernate

@enduml