@startuml stateDiagram
[*] --> Menu
Menu --> CardViewer : play
Menu --> CardEditor : new
Menu --> CardEditor : edit
Menu --> Settings : settings
CardViewer --> Menu : home
CardEditor --> Menu : home
CardViewer --> Settings : settings
CardEditor --> Settings : settings
[*] --> [*] : close

@enduml