site_name: ideacards docs

theme:
  language: de
  name: material
  features:
    - navigation.instant
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: white


markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      guess_lang: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search