site_name: CardIdea
site_url: https://elijahsey.github.io/cardidea
repo_name: cardidea
repo_url: https://github.com/ElijahSey/cardidea

theme:
  name: material
  language: de
  icon:
    repo: simple/github
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep-purple
      accent: deep-purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep-purple
      accent: deep-purple
  
  features:
    - content.code.copy       # Kopierenbutton für Codeblöcke
    - content.code.annotate   # Codeanmerkungen
    - navigation.instant
    - navigation.tracking     # die URL wird automatisch angepasst, wenn man herunterscrollt
    - navigation.tabs         # Navigationstabs werden angezeigt
    - navigation.tabs.sticky  # Navigationstabs bleiben dauerhaft sichtbar 
    - navigation.path         
    - navigation.indexes      
    - toc.follow              # Table of contents folgt dem Scrollen             
    - content.tooltips        # Enable tooltip functionality
    - content.action.edit     # Bearbeiten-Button auf jeder Seite
    - content.action.view     # Quellcode Anzeige auf jeder Seite
    - navigation.top          # Zurück zum Seitenanfang

nav:
  - Startseite: index.md
  - Anforderungen: 
    - Funktional: requirements/functional.md
    - Qualität: requirements/quality.md
  - Architektur:
    - Komponentendiagramm: architecture/componentDiagram.md
    - Zustandsdiagramm: architecture/stateDiagram.md
    - Klassendiagramm: architecture/classDiagram.md
  - CI/CD:
    - Continuous Integration: ci_cd/ci.md
    - Continuous Deployment: ci_cd/cd.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      guess_lang: true
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - style/extra.css

plugins:
  - search
  - build_plantuml:
      render: "server"
      bin_path: "/usr/local/bin/plantuml"
      server: "http://www.plantuml.com/plantuml"
      output_format: "svg"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"
      theme_enabled: true
      theme_folder: "include/themes"
      theme_light: "light.puml"
      theme_dark: "dark.puml"