name: Continuous Integration Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Check JRE
      run: |
        ls /usr/bin/java
        ls /usr/share/java
        ls /usr/lib/jvm/temurin-17-jdk-amd64/bin/java
    
    - name: Maven Build
      run: mvn resources:resources compiler:compile resources:testResources compiler:testCompile
      
    - name: Maven Unit Test
      run: mvn surefire:test
      
    - name: Maven Integration Test
      run: mvn failsafe:integration-test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v3
